import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RouteProvider from "./Context/RouteContext";
import ProtectedRoute from "./Components/Onboarding/HandleRoute";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <RouteProvider>
                    <ProtectedRoute>
                        {children}
                    </ProtectedRoute>
                </RouteProvider>
            </body>
        </html>
    );
}